"use client";

import dynamic from "next/dynamic";
import Link from "next/link";
import { useEffect, useMemo, useRef, useState } from "react";
import gsap from "gsap";
import { ScrollTrigger } from "gsap/ScrollTrigger";
import Lenis from "lenis";
import { SceneCanvas } from "@/components/site/SceneCanvas";
import { CustomCursor } from "@/components/site/CustomCursor";
import { useMediaQuery, usePageVisible } from "@/components/site/hooks";
import { blogPosts } from "@/data/blogPosts";

gsap.registerPlugin(ScrollTrigger);

const HeroSerpentScene = dynamic(() => import("@/components/scenes/HeroSerpentScene").then((m) => m.HeroSerpentScene), { ssr: false });
const ServicesGridScene = dynamic(() => import("@/components/scenes/ServicesGridScene").then((m) => m.ServicesGridScene), {
  ssr: false,
});
const AboutHeadScene = dynamic(() => import("@/components/scenes/AboutHeadScene").then((m) => m.AboutHeadScene), { ssr: false });
const ContactOrbScene = dynamic(() => import("@/components/scenes/ContactOrbScene").then((m) => m.ContactOrbScene), { ssr: false });

const services = [
  { icon: "📸", title: "AI Product Photography", body: "Studio-quality visuals. Zero studio." },
  { icon: "🎬", title: "AI Product Video Ads", body: "Scroll-stopping ads, generated by AI." },
  { icon: "💬", title: "AI WhatsApp Chatbots", body: "Your brand, always online, always converting." },
  { icon: "📱", title: "Social Media Management", body: "Strategy, content, growth — all handled." },
  { icon: "📊", title: "Ads Management", body: "Precision targeting. Maximum ROI." },
];

const workItems = [
  "Luma Skin — AI Photography",
  "Nova Snacks — AI Video Ad Suite",
  "Rivo Interiors — WhatsApp Bot Funnel",
  "Elan Jewellery — Paid Social System",
  "Kairo Tech — Product Story Engine",
  "Ora Foods — Omnichannel Ad Lab",
];

const testimonials = [
  { name: "Aarav Mehta", company: "Luma Retail", quote: "Zinway made our creative output feel unfairly fast." },
  { name: "Sara Khan", company: "Nexa Living", quote: "The WhatsApp bot became our best-performing sales rep." },
  { name: "Kabir Rao", company: "Fitrio", quote: "Performance marketing with cinematic creative precision." },
  { name: "Maya Singh", company: "Orga Beauty", quote: "Every campaign looked premium and converted better." },
  { name: "Vihaan Das", company: "Volt Commerce", quote: "From strategy to execution, the flow feels autonomous." },
];

const ticker = ["AI Photography", "AI Video Ads", "WhatsApp Chatbots", "Social Media", "Ads Management"];

function SplitTitle({ text }: { text: string }) {
  return (
    <span className="split-title" aria-label={text}>
      {text.split("").map((char, i) => (
        <span key={`${char}-${i}`} className="char" aria-hidden="true">
          {char === " " ? "\u00A0" : char}
        </span>
      ))}
    </span>
  );
}

function MagneticButton({ children, href }: { children: React.ReactNode; href: string }) {
  const ref = useRef<HTMLAnchorElement>(null);

  return (
    <Link
      href={href}
      className="btn magnetic"
      ref={ref}
      onMouseMove={(e) => {
        if (!ref.current) return;
        const rect = ref.current.getBoundingClientRect();
        const x = ((e.clientX - rect.left) / rect.width - 0.5) * 14;
        const y = ((e.clientY - rect.top) / rect.height - 0.5) * 14;
        ref.current.style.transform = `translate(${x}px, ${y}px)`;
      }}
      onMouseLeave={() => {
        if (ref.current) {
          ref.current.style.transform = "translate(0px, 0px)";
        }
      }}
    >
      {children}
    </Link>
  );
}

export default function Home() {
  const pageRef = useRef<HTMLDivElement>(null);
  const [scrolled, setScrolled] = useState(false);
  const isMobile = useMediaQuery("(max-width: 767px)");
  const reduced3D = useMediaQuery("(max-width: 1024px)");
  const visible = usePageVisible();
  const [pointer, setPointer] = useState({ x: 0, y: 0 });
  const [menuOpen, setMenuOpen] = useState(false);
  const [burst, setBurst] = useState(false);
  const workRef = useRef<HTMLDivElement>(null);
  const dragState = useRef({ active: false, startX: 0, startScroll: 0 });

  useEffect(() => {
    const lenis = new Lenis({ lerp: 0.1, smoothWheel: true, autoRaf: false });

    const raf = (time: number) => {
      lenis.raf(time);
      requestAnimationFrame(raf);
    };

    requestAnimationFrame(raf);
    lenis.on("scroll", ScrollTrigger.update);

    const reveals = gsap.utils.toArray<HTMLElement>(".reveal");
    reveals.forEach((el) => {
      gsap.fromTo(
        el,
        { y: 48, autoAlpha: 0 },
        { y: 0, autoAlpha: 1, duration: 0.9, ease: "power3.out", scrollTrigger: { trigger: el, start: "top 82%" } },
      );
    });

    gsap.utils.toArray<HTMLElement>(".split-title .char").forEach((el, index) => {
      gsap.fromTo(
        el,
        { y: 56, autoAlpha: 0 },
        {
          y: 0,
          autoAlpha: 1,
          duration: 0.7,
          delay: index * 0.015,
          ease: "power2.out",
          scrollTrigger: { trigger: el.closest("section") as Element, start: "top 80%" },
        },
      );
    });

    gsap.utils.toArray<HTMLElement>(".parallax").forEach((el) => {
      gsap.to(el, {
        yPercent: -20,
        ease: "none",
        scrollTrigger: { trigger: el, start: "top bottom", end: "bottom top", scrub: true },
      });
    });

    gsap.utils.toArray<HTMLElement>(".stat-value").forEach((el) => {
      const target = Number(el.dataset.value || "0");
      const obj = { value: 0 };
      gsap.to(obj, {
        value: target,
        duration: 1.6,
        ease: "power2.out",
        scrollTrigger: { trigger: el, start: "top 85%", once: true },
        onUpdate: () => {
          el.textContent = `${Math.round(obj.value)}${el.dataset.suffix ?? ""}`;
        },
      });
    });

    return () => {
      lenis.destroy();
      ScrollTrigger.getAll().forEach((trigger) => trigger.kill());
    };
  }, []);

  useEffect(() => {
    const onScroll = () => setScrolled(window.scrollY > 30);
    onScroll();
    window.addEventListener("scroll", onScroll);
    return () => window.removeEventListener("scroll", onScroll);
  }, []);

  const marqueeItems = useMemo(() => [...testimonials, ...testimonials], []);

  return (
    <div className="site" ref={pageRef} onMouseMove={(e) => setPointer({ x: (e.clientX / window.innerWidth - 0.5) * 2, y: (0.5 - e.clientY / window.innerHeight) * 2 })}>
      <CustomCursor />
      <div className="noise-overlay" />
      <div className="vignette-overlay" />

      <header className={`site-nav ${scrolled ? "is-scrolled" : ""}`}>
        <div className="container nav-inner">
          <Link href="#home" className="logo">
            <span className="snake-glyph">∿</span> ZINWAY
          </Link>
          <nav className={`nav-links ${menuOpen ? "is-open" : ""}`}>
            {[
              ["Home", "#home"],
              ["Services", "#services"],
              ["Work", "#work"],
              ["Pricing", "#pricing"],
              ["About", "#about"],
              ["Blog", "#blog"],
              ["Contact", "#contact"],
            ].map(([label, href]) => (
              <a key={href} href={href} onClick={() => setMenuOpen(false)}>
                {label}
              </a>
            ))}
            <MagneticButton href="#contact">Start Project →</MagneticButton>
          </nav>
          <button className={`hamburger ${menuOpen ? "is-open" : ""}`} onClick={() => setMenuOpen((v) => !v)} aria-label="Toggle menu">
            <span />
            <span />
            <span />
          </button>
        </div>
      </header>

      <main>
        <section className="hero" id="home">
          <SceneCanvas enabled={!isMobile} active={visible} className="hero-canvas">
            <HeroSerpentScene reduced={reduced3D} />
          </SceneCanvas>
          <div className="container hero-content">
            <p className="kicker reveal">Where Intelligence Meets Influence.</p>
            <h1 className="reveal">
              <SplitTitle text="ZINWAY" />
            </h1>
            <p className="hero-text reveal">A sentient AI marketing organism for brands that want dominance, not noise.</p>
            <div className="hero-ctas reveal">
              <a href="#services" className="btn btn-solid">
                Explore Services
              </a>
              <a href="#work" className="btn btn-ghost">
                See Our Work
              </a>
            </div>
          </div>
          <div className="ticker" aria-label="Services ticker">
            <div className="ticker-track">
              {[...ticker, ...ticker, ...ticker].map((item, i) => (
                <span key={`${item}-${i}`}>{item} •</span>
              ))}
            </div>
          </div>
        </section>

        <section className="section services" id="services">
          <SceneCanvas enabled={!isMobile} active={visible} className="services-canvas parallax">
            <ServicesGridScene />
          </SceneCanvas>
          <div className="container">
            <h2 className="reveal">
              <SplitTitle text="What We Do" />
            </h2>
            <div className="service-grid">
              {services.map((service) => (
                <article key={service.title} className="service-card reveal">
                  <div className="service-card-inner">
                    <div className="service-front">
                      <span>{service.icon}</span>
                      <h3>{service.title}</h3>
                    </div>
                    <div className="service-back">
                      <p>{service.body}</p>
                    </div>
                  </div>
                </article>
              ))}
            </div>
          </div>
        </section>

        <section className="section work" id="work">
          <div className="container">
            <h2 className="reveal">Selected Work</h2>
            <div
              className="work-track"
              ref={workRef}
              onWheel={(e) => {
                if (!workRef.current) return;
                e.preventDefault();
                workRef.current.scrollLeft += e.deltaY;
              }}
              onPointerDown={(e) => {
                if (!workRef.current) return;
                dragState.current = { active: true, startX: e.clientX, startScroll: workRef.current.scrollLeft };
              }}
              onPointerMove={(e) => {
                if (!dragState.current.active || !workRef.current) return;
                workRef.current.scrollLeft = dragState.current.startScroll - (e.clientX - dragState.current.startX);
              }}
              onPointerUp={() => {
                dragState.current.active = false;
              }}
              onPointerLeave={() => {
                dragState.current.active = false;
              }}
            >
              {workItems.map((item, i) => (
                <article key={item} className="work-card reveal">
                  <div className="work-media" style={{ backgroundImage: `linear-gradient(140deg, rgba(0,255,106,0.25), rgba(2,10,5,0.8)), url(https://picsum.photos/seed/zinway-${i}/1100/700)` }} />
                  <div className="work-meta">
                    <span className="tag-chip">{i % 2 ? "Video Ads" : "AI Photography"}</span>
                    <h3>{item}</h3>
                    <MagneticButton href="#contact">View Project</MagneticButton>
                  </div>
                </article>
              ))}
            </div>
          </div>
        </section>

        <section className="section pricing" id="pricing">
          <div className="container">
            <h2 className="reveal">Pricing Intelligence</h2>
            <div className="pricing-grid">
              {[
                { tier: "Starter", desc: "Essentials for small businesses", popular: false },
                { tier: "Growth ⭐", desc: "Most Popular — full suite for scaling brands", popular: true },
                { tier: "Enterprise", desc: "Custom everything for large operations", popular: false },
              ].map(({ tier, desc, popular }) => (
                <article key={tier} className={`pricing-card reveal ${popular ? "is-popular" : ""}`}>
                  <h3>{tier}</h3>
                  <p>{desc}</p>
                  <ul>
                    {["AI creatives", "Campaign automation", "Weekly optimizations"].map((f) => (
                      <li key={f}>
                        <svg width="18" height="18" viewBox="0 0 18 18" fill="none" aria-hidden="true">
                          <path d="M3 9.5L7 13L15 4" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" />
                        </svg>
                        {f}
                      </li>
                    ))}
                  </ul>
                  <button
                    className="btn btn-solid"
                    onClick={() => {
                      setBurst(true);
                      setTimeout(() => setBurst(false), 450);
                    }}
                  >
                    Get Started
                  </button>
                  {burst && <span className="particle-burst" />}
                </article>
              ))}
            </div>
          </div>
        </section>

        <section className="section about" id="about">
          <div className="container about-grid">
            <SceneCanvas enabled={!isMobile} active={visible} className="about-canvas">
              <AboutHeadScene />
            </SceneCanvas>
            <div>
              <h2 className="reveal">We Are The Algorithm.</h2>
              <p className="reveal">
                Zinway is not just an agency. We are an intelligence engine built to transform how brands grow in the digital age. We combine
                cutting-edge AI with human creativity to deliver results that feel like magic — but are pure data.
              </p>
              <div className="stats reveal">
                <div>
                  <p className="stat-value" data-value="200" data-suffix="+">
                    0+
                  </p>
                  <small>Brands Scaled</small>
                </div>
                <div>
                  <p className="stat-value" data-value="10" data-suffix="M+">
                    0M+
                  </p>
                  <small>Impressions Generated</small>
                </div>
                <div>
                  <p className="stat-value" data-value="98" data-suffix="%">
                    0%
                  </p>
                  <small>Client Retention</small>
                </div>
              </div>
            </div>
          </div>
        </section>

        <section className="section testimonials" id="testimonials">
          <div className="container">
            <h2 className="reveal">Client Signals</h2>
          </div>
          <div className="marquee-row left">
            <div className="marquee-track">
              {marqueeItems.map((t, i) => (
                <article className="testimonial-card" key={`${t.name}-${i}`}>
                  <strong>{t.name}</strong>
                  <span>{t.company}</span>
                  <p>★★★★★</p>
                  <blockquote>{t.quote}</blockquote>
                </article>
              ))}
            </div>
          </div>
          <div className="marquee-row right">
            <div className="marquee-track">
              {marqueeItems.map((t, i) => (
                <article className="testimonial-card" key={`${t.company}-${i}`}>
                  <strong>{t.name}</strong>
                  <span>{t.company}</span>
                  <p>★★★★★</p>
                  <blockquote>{t.quote}</blockquote>
                </article>
              ))}
            </div>
          </div>
        </section>

        <section className="section contact" id="contact">
          <SceneCanvas enabled={!isMobile} active={visible} className="contact-canvas">
            <ContactOrbScene pointer={pointer} />
          </SceneCanvas>
          <div className="container contact-content">
            <h2 className="reveal">Ready to Evolve?</h2>
            <p className="reveal">Let&apos;s build something the market has never seen.</p>
            <form className="contact-form reveal">
              <input placeholder="Name" />
              <input placeholder="Email" type="email" />
              <select defaultValue="">
                <option value="" disabled>
                  Service Interested In
                </option>
                {services.map((service) => (
                  <option key={service.title}>{service.title}</option>
                ))}
              </select>
              <textarea placeholder="Message" rows={4} />
              <button type="submit" className="btn btn-solid">
                Send Inquiry
              </button>
            </form>
            <div className="contact-actions reveal">
              <a href="https://wa.me/0000000000" className="btn btn-ghost magnetic" target="_blank" rel="noopener noreferrer">
                Chat on WhatsApp 🐍
              </a>
              <div className="social-row">
                {[
                  ["Instagram", "https://instagram.com"],
                  ["LinkedIn", "https://linkedin.com"],
                  ["Twitter/X", "https://x.com"],
                ].map(([label, href]) => (
                  <a key={label} href={href} className="magnetic" target="_blank" rel="noopener noreferrer">
                    {label}
                  </a>
                ))}
              </div>
            </div>
          </div>
        </section>

        <section className="section blog" id="blog">
          <div className="container">
            <p className="kicker reveal">Insights from the edge of AI marketing</p>
            <h2 className="reveal">Intelligence Dispatches</h2>
            <div className="blog-grid">
              {blogPosts.map((post) => (
                <article key={post.slug} className="blog-card reveal">
                  <div className="card-image" style={{ backgroundImage: `url(${post.image})` }} />
                  <div className="card-content">
                    <span className="tag-chip">{post.tag}</span>
                    <h3>{post.title}</h3>
                    <p>{post.readTime}</p>
                    <Link href={`/blog/${post.slug}`}>Read article →</Link>
                  </div>
                </article>
              ))}
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
